In [1]:
import pandas as pd
import geopandas as gpd
import numpy as np

/usr/local/lib/python3.8/dist-packages/geopandas/_compat.py:106: UserWarning: The Shapely GEOS version (3.8.0-CAPI-1.13.1 ) is incompatible with the GEOS version PyGEOS was compiled with (3.10.1-CAPI-1.16.0). Conversions between both will be slow.
  warnings.warn(

In [2]:
gdf_small = gpd.read_file('../shape_data/dataset_plots.geojson')
gdf = gpd.read_file('../shape_data/full_dataset.geojson')

In [3]:
gdf_small

,Plot_ID,t_С,t_Л,t_Б,t_ОС,t_Е,t_П,t_К,t_Клас,t_Class,geometry
0,14.0,0.813953,0.000000,0.116279,0.069767,0.000000,0.0,0.000000,С,7,"MULTIPOLYGON (((656854.099 6275926.535, 656855..."
1,27.0,0.767857,0.035714,0.107143,0.089286,0.000000,0.0,0.000000,С,7,"MULTIPOLYGON (((662190.184 6278821.988, 662191..."
2,29.0,0.020408,0.000000,0.173469,0.806122,0.000000,0.0,0.000000,ОС,5,"MULTIPOLYGON (((657773.933 6280454.568, 657775..."
3,31.0,0.681818,0.022727,0.136364,0.000000,0.045455,0.0,0.113636,С,7,"MULTIPOLYGON (((660102.838 6280175.395, 660104..."
4,34.0,0.000000,0.000000,0.885417,0.000000,0.114583,0.0,0.000000,Б,1,"MULTIPOLYGON (((655012.854 6283465.079, 655014..."
...,...,...,...,...,...,...,...,...,...,...,...
283,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,15,"MULTIPOLYGON (((660559.471 6272971.605, 660560..."
284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,15,"MULTIPOLYGON (((660110.616 6274651.790, 660111..."
285,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,15,"MULTIPOLYGON (((659932.835 6274533.493, 659933..."
286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,15,"MULTIPOLYGON (((659649.440 6273708.148, 659649..."
287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,15,"MULTIPOLYGON (((660342.965 6274427.546, 660343..."

In [7]:
gdf[['EL_PRC', 'KEDR_PRC', 'LSTV_PRC','PICH_PRC', 'SOS_PRC', 'BER_PRC', 'OS_PRC']]

     EL_PRC  KEDR_PRC  LSTV_PRC  PICH_PRC  SOS_PRC  BER_PRC  OS_PRC
0      26.0       6.0      38.0       0.0     17.0     14.0     0.0
1       0.0       0.0       0.0       0.0      0.0      8.0    92.0
2       0.0       0.0       1.0       0.0     85.0     13.0     1.0
3       0.0       0.0       3.0       0.0      0.0     56.0    40.0
4      38.0      29.0       0.0      26.0      0.0      7.0     0.0
..      ...       ...       ...       ...      ...      ...     ...
891     0.0       0.0      14.0       0.0     38.0     43.0     4.0
892     0.0       0.0       0.0       3.0      0.0      9.0    87.0
893     0.0       0.0       0.0       3.0      0.0     17.0    80.0
894     0.0       0.0      12.0       0.0      7.0     68.0     5.0
895     0.0       8.0       0.0      58.0     19.0      0.0    15.0

[896 rows x 7 columns]

In [44]:
gdf_small.loc[mask].reset_index(drop=True).iloc[:, -3:]

     t_Клас  t_Class                                           geometry
0     земля       12  MULTIPOLYGON (((671121.922 6273169.820, 671419...
1     трава       14  MULTIPOLYGON (((675860.652 6283851.481, 676272...
2      гарь       15  MULTIPOLYGON (((659745.714 6273736.714, 659895...
3    болото       16  MULTIPOLYGON (((660375.992 6273671.959, 660434...
4   вырубки       13  MULTIPOLYGON (((671620.069 6290981.428, 671621...
..      ...      ...                                                ...
60     None       15  MULTIPOLYGON (((660559.471 6272971.605, 660560...
61     None       15  MULTIPOLYGON (((660110.616 6274651.790, 660111...
62     None       15  MULTIPOLYGON (((659932.835 6274533.493, 659933...
63     None       15  MULTIPOLYGON (((659649.440 6273708.148, 659649...
64     None       15  MULTIPOLYGON (((660342.965 6274427.546, 660343...

[65 rows x 3 columns]

In [45]:
mask = gdf_small['t_Class']>8
gdf_small.loc[mask].reset_index(drop=True).iloc[:, -3:].to_file('../shape_data/non_forest.geojson',driver='GeoJSON')

In [8]:
def get_dataset(threshold: float=80):
    rename = {"SOS_PRC": "С",
            "OS_PRC": "ОС",
            "BER_PRC": "Б",
            "PICH_PRC": "П",
            "EL_PRC": "Е",
            "KEDR_PRC": "К",
            "LSTV_PRC": "Л"}

    code_class = {'С': 7,
           'ОС': 5,
           'Б': 1,
           'П': 6,
           'Е': 2,
           'К': 3,
           'Л': 4}
    
    target_cols = ['EL_PRC', 'KEDR_PRC', 'LSTV_PRC','PICH_PRC', 'SOS_PRC', 'BER_PRC', 'OS_PRC']

    mask = gdf[target_cols]>threshold
    select=gdf.loc[mask.any(axis=1)].copy()
    t = select.loc[:, target_cols].idxmax(axis=1)
    select.loc[:, 't'] = select.loc[:, target_cols].idxmax(axis=1)
    select.loc[:, 't_Клас'] = select['t'].apply(lambda x : rename[x])
    select.loc[:, 't_Class'] = select['t_Клас'].apply(lambda x : code_class[x])
    select.pop('t')
    non_forest[select.columns[:-4]] = 1
    select = pd.concat([select, non_forest[select.columns]])
    return select

In [9]:
select = get_dataset(threshold=40)

NameError: name 'non_forest' is not defined

In [10]:
non_forest = gpd.read_file('../shape_data/non_forest.geojson')

In [58]:
non_forest[select.columns[:-3]] = 1

In [59]:
select = pd.concat([select, non_forest[select.columns]])

In [22]:
pd.DataFrame(data = np.zeros(shape=noa
                            )select.columns[:-4]

Index(['Plot_ID', 'xc', 'yc', 'Plot_ID_1', 'HDOM_check', 'HGW_check', 'HGW',
       'HGW11', 'HGW12', 'HGW13', 'HGW14', 'HGW15', 'HGW21', 'HGW22', 'HGW24',
       'HGW25', 'DGW', 'DGW11', 'DGW12', 'DGW13', 'DGW14', 'DGW15', 'DGW21',
       'DGW22', 'DGW24', 'DGW25', 'AGE', 'AGE11', 'AGE12', 'AGE13', 'AGE14',
       'AGE15', 'AGE21', 'AGE22', 'AGE24', 'AGE25', 'V', 'V11', 'V12', 'V13',
       'V14', 'V15', 'V21', 'V22', 'V24', 'V25', 'N', 'N11', 'N12', 'N13',
       'N14', 'N15', 'N21', 'N22', 'N24', 'N25', 'G', 'G11', 'G12', 'G13',
       'G14', 'G15', 'G21', 'G22', 'G24', 'G25', 'V_LARCH', 'V_BIRCH',
       'V_ASPEN', 'V_PINUS', 'V_SPRFIR', 'EL_PRC', 'KEDR_PRC', 'LSTV_PRC',
       'PICH_PRC', 'SOS_PRC', 'BER_PRC', 'OS_PRC', 'V_PRC_ALL'],
      dtype='object')

In [41]:
non_forest

,t_К,t_Клас,t_Class,geometry,Plot_ID,xc,yc,Plot_ID_1,HDOM_check,HGW_check,...,V_ASPEN,V_PINUS,V_SPRFIR,EL_PRC,KEDR_PRC,LSTV_PRC,PICH_PRC,SOS_PRC,BER_PRC,OS_PRC
0,None,земля,12,"MULTIPOLYGON (((671121.922 6273169.820, 671419...",1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
1,None,трава,14,"MULTIPOLYGON (((675860.652 6283851.481, 676272...",1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2,None,гарь,15,"MULTIPOLYGON (((659745.714 6273736.714, 659895...",1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
3,None,болото,16,"MULTIPOLYGON (((660375.992 6273671.959, 660434...",1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
4,None,вырубки,13,"MULTIPOLYGON (((671620.069 6290981.428, 671621...",1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,None,None,15,"MULTIPOLYGON (((660559.471 6272971.605, 660560...",1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
61,None,None,15,"MULTIPOLYGON (((660110.616 6274651.790, 660111...",1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
62,None,None,15,"MULTIPOLYGON (((659932.835 6274533.493, 659933...",1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
63,None,None,15,"MULTIPOLYGON (((659649.440 6273708.148, 659649...",1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
64,None,None,15,"MULTIPOLYGON (((660342.965 6274427.546, 660343...",1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [123]:
init_cols = ['t_С', 't_Л', 't_Б', 't_ОС', 't_Е','t_П', 't_К', 't_Клас']

target_cols = ['EL_PRC', 'KEDR_PRC', 'LSTV_PRC','PICH_PRC', 'SOS_PRC', 'BER_PRC', 'OS_PRC']

mask = gdf[target_cols]>50
select=gdf.loc[mask.any(axis=1)].copy()
t = select.loc[:, target_cols].idxmax(axis=1)
select.loc[:, 't'] = select.loc[:, target_cols].idxmax(axis=1)

In [140]:
rename = {"SOS_PRC": "С",
        "OS_PRC": "ОС",
        "BER_PRC": "Б",
        "PICH_PRC": "П",
        "EL_PRC": "Е",
        "KEDR_PRC": "К",
        "LSTV_PRC": "Л"}

code_class = {'С': 7,
       'ОС': 5,
       'Б': 1,
       'П': 6,
       'Е': 2,
       'К': 3,
       'Л': 4}
select.loc[:, 't_Клас'] = select['t'].apply(lambda x : rename[x])
select.loc[:, 't_Class'] = select['t_Клас'].apply(lambda x : code_class[x])

In [141]:
select

,Plot_ID,xc,yc,Plot_ID_1,HDOM_check,HGW_check,HGW,HGW11,HGW12,HGW13,...,LSTV_PRC,PICH_PRC,SOS_PRC,BER_PRC,OS_PRC,V_PRC_ALL,geometry,t,t_Клас,t_Class
1,2,6239502.885,322570.035,2,23.474036,21.372625,21.467685,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,8.0,92.0,100.0,"MULTIPOLYGON (((694125.371 6240239.543, 694126...",OS_PRC,ОС,5
2,3,6277777.327,285378.869,3,24.470646,21.391274,21.487636,0.000000,0.000000,14.900000,...,1.0,0.0,85.0,13.0,1.0,100.0,"MULTIPOLYGON (((653743.455 6275122.880, 653745...",SOS_PRC,С,7
3,4,6276577.352,286238.754,4,23.946989,21.873511,21.873511,0.000000,0.000000,16.700000,...,3.0,0.0,0.0,56.0,40.0,99.0,"MULTIPOLYGON (((654704.588 6274002.886, 654706...",BER_PRC,Б,1
5,6,6276595.872,288634.312,6,23.033333,19.593722,20.014820,0.000000,0.000000,0.000000,...,0.0,0.0,54.0,15.0,31.0,100.0,"MULTIPOLYGON (((657088.767 6274230.470, 657090...",SOS_PRC,С,7
6,7,6276447.199,289622.827,7,21.591821,14.056187,14.059062,10.508997,12.179129,0.000000,...,0.0,33.0,0.0,52.0,3.0,99.0,"MULTIPOLYGON (((658086.248 6274168.702, 658087...",BER_PRC,Б,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,894,6282252.830,310661.360,894,9.461896,9.718283,9.808914,0.000000,5.900000,0.000000,...,0.0,57.0,0.0,35.0,0.0,100.0,"MULTIPOLYGON (((678534.297 6281788.861, 678535...",PICH_PRC,П,6
892,897,6282052.739,310460.665,897,14.857800,12.121362,12.121362,0.000000,0.000000,0.000000,...,0.0,3.0,0.0,9.0,87.0,99.0,"MULTIPOLYGON (((678351.863 6281572.009, 678353...",OS_PRC,ОС,5
893,898,6281853.516,310461.319,898,15.184753,12.133869,12.130831,0.000000,0.000000,0.000000,...,0.0,3.0,0.0,17.0,80.0,100.0,"MULTIPOLYGON (((678369.922 6281373.615, 678371...",OS_PRC,ОС,5
894,899,6281852.705,310661.794,899,12.819511,11.306571,11.306571,0.000000,0.000000,12.669989,...,12.0,0.0,7.0,68.0,5.0,92.0,"MULTIPOLYGON (((678569.691 6281390.324, 678571...",BER_PRC,Б,1
895,900,6281851.505,310860.288,900,18.667257,15.768211,15.768211,0.000000,17.000000,0.000000,...,0.0,58.0,19.0,0.0,15.0,100.0,"MULTIPOLYGON (((678767.521 6281406.472, 678769...",PICH_PRC,П,6

In [139]:
gdf_small[['t_Клас', 't_Class']].drop_duplicates(subset='t_Клас').values

array([['С', 7],
       ['ОС', 5],
       ['Б', 1],
       ['П', 6],
       ['Е', 2],
       ['К', 3],
       ['Л', 4],
       ['земля', 12],
       ['трава', 14],
       ['гарь', 15],
       ['болото', 16],
       ['вырубки', 13],
       [None, 13]], dtype=object)

In [ ]:
{"SOS_PRC": "С"
"OS_PRC": "ОС"
"BER_PRC": "Б"
"PICH_PRC": "П"
"EL_PRC": "Е"
"KEDR_PRC": "К"
"LSTV_PRC": "Л"}

In [ ]:
    "С": "Pine",
    "Е": "Fir",
    "ОС": "Aspen",
    "К": "Cedar",
    "Л": "Larch",
    "Б": "Birch",
    "П": "Silver fir",

In [39]:
non_forest = {
    "вода": 11,
    "болото": 16,
    "вырубка": 13,
    "гарь": 15,
    "земля": 12,
    "трава": 14,
}

dictRename = {
    "С": "Pine",
    "Е": "Fir",
    "ОС": "Aspen",
    "К": "Cedar",
    "Л": "Larch",
    "Б": "Birch",
    "П": "Silver fir",
    "гарь": "Burnt forest",
    "вырубка": "Deforestation",
    "трава": "Grass",
    "земля": "Soil",
    "болото": "Swamp",
    "вода": "Water body",
}

,Plot_ID,t_С,t_Л,t_Б,t_ОС,t_Е,t_П,t_К,t_Клас,t_Class,geometry
0,14.0,0.813953,0.000000,0.116279,0.069767,0.000000,0.0,0.000000,С,7,"MULTIPOLYGON (((656854.099 6275926.535, 656855..."
1,27.0,0.767857,0.035714,0.107143,0.089286,0.000000,0.0,0.000000,С,7,"MULTIPOLYGON (((662190.184 6278821.988, 662191..."
2,29.0,0.020408,0.000000,0.173469,0.806122,0.000000,0.0,0.000000,ОС,5,"MULTIPOLYGON (((657773.933 6280454.568, 657775..."
3,31.0,0.681818,0.022727,0.136364,0.000000,0.045455,0.0,0.113636,С,7,"MULTIPOLYGON (((660102.838 6280175.395, 660104..."
4,34.0,0.000000,0.000000,0.885417,0.000000,0.114583,0.0,0.000000,Б,1,"MULTIPOLYGON (((655012.854 6283465.079, 655014..."
...,...,...,...,...,...,...,...,...,...,...,...
283,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,15,"MULTIPOLYGON (((660559.471 6272971.605, 660560..."
284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,15,"MULTIPOLYGON (((660110.616 6274651.790, 660111..."
285,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,15,"MULTIPOLYGON (((659932.835 6274533.493, 659933..."
286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,15,"MULTIPOLYGON (((659649.440 6273708.148, 659649..."
287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,15,"MULTIPOLYGON (((660342.965 6274427.546, 660343..."

In [28]:
gdf_small.describe().iloc[1:3, 1:-1]

           t_С       t_Л       t_Б      t_ОС       t_Е       t_П       t_К
mean  0.173757  0.084505  0.267409  0.269255  0.059728  0.111774  0.033571
std   0.319397  0.213399  0.343283  0.394584  0.142300  0.239334  0.100683

In [13]:

gdf.mean(axis=0)

/var/folders/1f/xyznj37x1n337kxt0v5533rw0000gn/T/ipykernel_99868/1563689046.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  gdf.mean(axis=0)

Plot_ID       4.510078e+02
xc            6.288586e+06
yc            3.003658e+05
Plot_ID_1     4.507712e+02
HDOM_check    2.190534e+01
                  ...
PICH_PRC      1.022956e+01
SOS_PRC       2.538746e+01
BER_PRC       2.348040e+01
OS_PRC        2.158343e+01
V_PRC_ALL     9.947032e+01
Length: 79, dtype: float64

In [11]:
for col in gdf.columns:
    print(col, np.round(gdf[col].mean(), 2))

Plot_ID 451.01
xc 6288586.22
yc 300365.82
Plot_ID_1 450.77
HDOM_check 21.91
HGW_check 18.15
HGW 18.09
HGW11 7.98
HGW12 7.35
HGW13 8.59
HGW14 8.49
HGW15 12.14
HGW21 15.25
HGW22 1.8
HGW24 0.28
HGW25 11.4
DGW 20.49
DGW11 8.19
DGW12 8.67
DGW13 10.35
DGW14 9.03
DGW15 15.54
DGW21 13.56
DGW22 1.67
DGW24 0.23
DGW25 11.79
AGE 78.52
AGE11 44.42
AGE12 41.01
AGE13 41.64
AGE14 45.03
AGE15 59.31
AGE21 53.97
AGE22 4.97
AGE24 0.4
AGE25 36.56
V 251.2
V11 14.51
V12 11.76
V13 24.93
V14 24.86
V15 71.24
V21 45.18
V22 0.63
V24 0.05
V25 58.05
N 1696.48
N11 113.95
N12 92.37
N13 57.88
N14 283.9
N15 339.3
N21 488.57
N22 18.47
N24 2.54
N25 299.51
G 28.06
G11 1.65
G12 1.45
G13 2.14
G14 3.57
G15 7.48
G21 5.76
G22 0.13
G24 0.01
G25 5.86
V_LARCH 24.93
V_BIRCH 45.18
V_ASPEN 58.05
V_PINUS 83.0
V_SPRFIR 39.37
EL_PRC 5.97
KEDR_PRC 4.88
LSTV_PRC 7.93
PICH_PRC 10.23
SOS_PRC 25.39
BER_PRC 23.48
OS_PRC 21.58
V_PRC_ALL 99.47

TypeError: cannot perform mean with type geometry